import numpy as np

def decisionTree (data,attr_list):
    if data[attr_list.index("rimmx")]=="f":
        if data[attr_list.index("bxqsq")]=="f":
            if data[attr_list.index("wknck")]=="f":
                if data[attr_list.index("wkna8")]=="f":
                    if data[attr_list.index("bkxbq")]=="f":
                        if data[attr_list.index("wkpos")]=="t":
                            if data[attr_list.index("katri")]=="n":
                                if data[attr_list.index("rxmsq")]=="f":
                                    if data[attr_list.index("dsopp")]=="f":
                                        return  "won"
                                    elif data[attr_list.index("dsopp")]=="t":
                                        if data[attr_list.index("dwipd")]=="l":
                                            return  "won"
                                        elif data[attr_list.index("dwipd")]=="g":
                                            if data[attr_list.index("blxwp")]=="t":
                                                return  "won"
                                            elif data[attr_list.index("blxwp")]=="f":
                                                if data[attr_list.index("skewr")]=="f":
                                                    return  "won"
                                                elif data[attr_list.index("skewr")]=="t":
                                                    return  "nowin"
                                elif data[attr_list.index("rxmsq")]=="t":
                                        if data[attr_list.index("qxmsq")]=="t":
                                            return  "won"
                                        if data[attr_list.index("qxmsq")]=="f":
                                            return  "nowin"
                            if data[attr_list.index("katri")]=="w":
                                return  "won"
                            elif data[attr_list.index("katri")]=="b":
                                if data[attr_list.index("bkblk")]=="t":
                                    return  "won"
                                if data[attr_list.index("bkblk")]=="f":
                                    return  "nowin"
                        if data[attr_list.index("wkpos")]=="f":
                            if data[attr_list.index("katri")]=="w":
                                return  "won"
                            elif data[attr_list.index("katri")]=="n":
                                if data[attr_list.index("bkblk")]=="t":
                                    if data[attr_list.index("hdchk")]=="f":
                                        return  "won"
                                    if data[attr_list.index("hdchk")]=="t":
                                        return  "nowin"
                                elif data[attr_list.index("bkblk")]=="f":
                                    if data[attr_list.index("dsopp")]=="f":
                                        return  "nowin"
                                    if data[attr_list.index("dsopp")]=="t":
                                        ['f', 't']
                                        if data[attr_list.index("r2ar8")]=="f":
                                            if data[attr_list.index("reskr")]=="f":
                                                return  "won"
                                            if data[attr_list.index("reskr")]=="t":
                                                return  "nowin"
                                        elif data[attr_list.index("r2ar8")]=="t":
                                            return  "nowin"
                            elif data[attr_list.index("katri")]=="b":
                                if data[attr_list.index("bkblk")]=="t":
                                    if data[attr_list.index("hdchk")]=="f":
                                        return  "won"
                                    elif data[attr_list.index("hdchk")]=="t":
                                        return  "nowin"
                                elif data[attr_list.index("bkblk")]=="f":
                                    return  "nowin"
                    elif data[attr_list.index("bkxbq")]=="t":
                        return  "won"
                if data[attr_list.index("wkna8")]=="t":
                    if data[attr_list.index("bknwy")]=="f":
                        return  "nowin"
                    elif data[attr_list.index("bknwy")]=="t":
                        if data[attr_list.index("wkovl")]=="t":
                            if data[attr_list.index("katri")]=="n":
                                return  "won"
                            if data[attr_list.index("katri")]=="b":
                                return  "nowin"
                        if data[attr_list.index("wkovl")]=="f":
                            return  "nowin"
            if data[attr_list.index("wknck")]=="t":
                if data[attr_list.index("wkovl")]=="f":
                    if data[attr_list.index("bkxcr")]=="f":
                        if data[attr_list.index("skrxp")]=="f":
                            if data[attr_list.index("mulch")]=="f":
                                if data[attr_list.index("bkona")]=="f":
                                    if data[attr_list.index("thrsk")]=="f":
                                        if data[attr_list.index("bkon8")]=="f":
                                            if data[attr_list.index("skach")]=="f":
                                                if data[attr_list.index("blxwp")]=="f":
                                                    return  "won"
                                                elif data[attr_list.index("blxwp")]=="t":
                                                    return  "nowin"
                                            elif data[attr_list.index("skach")]=="t":
                                                return  "nowin"
                                        elif data[attr_list.index("bkon8")]=="t":
                                            return  "nowin"
                                    elif data[attr_list.index("thrsk")]=="t":
                                        return  "nowin"
                                elif data[attr_list.index("bkona")]=="t":
                                    return  "nowin"
                            elif data[attr_list.index("mulch")]=="t":
                                return  "nowin"
                        elif data[attr_list.index("skrxp")]=="t":
                            return  "nowin"
                    elif data[attr_list.index("bkxcr")]=="t":
                        return  "nowin"
                elif data[attr_list.index("wkovl")]=="t":
                    if data[attr_list.index("bknwy")]=="f":
                        return  "nowin"
                    elif data[attr_list.index("bknwy")]=="t":
                            if data[attr_list.index("mulch")]=="f":
                                return  "won"
                            elif data[attr_list.index("mulch")]=="t":
                                return  "nowin"
        elif data[attr_list.index("bxqsq")]=="t":
            return  "nowin"
    elif data[attr_list.index("rimmx")]=="t":
        return  "won"
